import { ModeToggle } from '@/components/ModeToggle';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Admin Dash',
	description: 'Generated by create next app',
};

export default async function AuthenticatedLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			className='relative h-screen flex-col items-center justify-center grid grid-cols-1 mx-8 sm:mx-0 lg:max-w-none lg:grid-cols-2 lg:px-0'
			style={{
				background: 'url("/download.svg") center center / cover no-repeat',
			}}
		>
			<div className='lg:p-8 '>
				<div className='mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[500px] lg:w-[450px]'>
					{children}
				</div>
			</div>
			<div
				className='relative hidden h-full flex-col bg-muted p-10 text-white lg:flex dark:border-r'
				style={{
					background: 'url("/login.jpg") center center / cover no-repeat',
				}}
			/>
			<div className='absolute right-4 bottom-4 md:right-8 md:bottom-8 flex items-center gap-2'>
				<ModeToggle className='bg-transparent backdrop-blur-md' />
			</div>
		</div>
	);
}
